spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: zero1234
  batch:
    jdbc:
      initialize-schema: always